security:
    encoders:
          AppBundle\Entity\Users:
            plaintext
    providers:
          doctrine:
            entity:
              class: AppBundle:Users
              property: cidentificator


    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            form_login:
               login_path: login
               check_path: login
               default_target_path: home
            provider: doctrine

            logout:
              path: logout
              target: login


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }